DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS searches;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE searches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  search_name TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);